apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leo.fullname" . }}
  labels:
    {{- include "leo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "leo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "leo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.leo.image }}:{{ .Values.leo.tag }}"
          imagePullPolicy: {{ .Values.leo.pullPolicy }}
          env:
            {{- range $key, $value := .Values.leo.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # Add environment variables from secrets
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "leo.fullname" . }}
                  key: OPENAI_API_KEY
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "leo.fullname" . }}
                  key: SLACK_BOT_TOKEN
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "leo.fullname" . }}
                  key: SLACK_APP_TOKEN
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }} 