apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "leo.fullname" . }}
  labels:
    app: {{ template "leo.name" . }}
    chart: {{ template "leo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: github-secrets
  target:
    name: {{ template "leo.fullname" . }}
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: OPENAI_API_KEY
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: SLACK_BOT_TOKEN
    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: SLACK_APP_TOKEN