replicaCount: 1

leo:
  image: leo  # This will be overridden in the workflow
  tag: latest
  environment: production
  # set to never when using local images
  pullPolicy: Always
  # Optional environment variables
  env:
    MAX_SUMMARY_BULLETS: "5"
    OPENAI_TEMPERATURE: "0.5"

imagePullSecrets: []  # This will be set by --set in the workflow

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

nodeSelector: {}

affinity: {}

# Service account configuration
serviceAccount:
  create: false
  name: ""
