name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      actions: read

    steps:
    - uses: actions/checkout@v4

    - name: Generate GitHub token
      id: generate_token
      run: |
        echo "token=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/leo:latest
        context: .

    - name: Verify image push
      run: |
        # Try to pull the image to verify it was pushed
        docker pull ghcr.io/${{ github.repository_owner }}/leo:latest
        # Show image details
        docker inspect ghcr.io/${{ github.repository_owner }}/leo:latest

    - name: Make package public
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Make the package public
        curl -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          https://api.github.com/user/packages/container/leo/visibility \
          -d '{"visibility":"public"}'

    - name: Setup kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Create secrets
      run: |
        # Create image pull secret with base64 encoded token
        kubectl delete secret ghcr-secret --ignore-not-found
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=$(echo ${{ steps.generate_token.outputs.token }}) \
          --docker-email=${{ github.actor }}@users.noreply.github.com

        # Create application secrets
        kubectl delete secret leo --ignore-not-found
        kubectl create secret generic leo \
          --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          --from-literal=SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} \
          --from-literal=SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }}

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install leo ./helm/leo \
          --set leo.image=ghcr.io/${{ github.repository_owner }}/leo \
          --set leo.pullPolicy=Always \
          --set imagePullSecrets[0].name=ghcr-secret

    - name: Debug deployment
      run: |
        echo "Pod details:"
        kubectl get pods -l app.kubernetes.io/name=leo -o wide
        echo "\nPod description:"
        kubectl describe pod -l app.kubernetes.io/name=leo
        echo "\nSecret details (redacted):"
        kubectl get secret ghcr-secret -o yaml | grep -v "dockerconfigjson:" 