name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/leo:latest
        context: .
        provenance: false

    - name: Setup kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Create image pull secret
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }} \
          --docker-email=${{ github.actor }}@users.noreply.github.com \
          --namespace=default

    - name: Apply ExternalSecret
      run: |
        # First apply the ExternalSecret
        helm template leo ./helm/leo -s templates/externalsecret.yaml | kubectl apply -f -
        
        # Wait for the secret to be created
        echo "Waiting for secret to be created..."
        for i in {1..30}; do
          if kubectl get secret leo -n default; then
            echo "Secret 'leo' created successfully"
            break
          fi
          echo "Waiting for secret to be created... attempt $i"
          sleep 10
        done

    - name: Verify Secrets
      run: |
        echo "Checking if required secrets exist..."
        kubectl get secret leo -n default

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install leo ./helm/leo \
          --set leo.image=ghcr.io/${{ github.repository_owner }}/leo \
          --set leo.pullPolicy=Always \
          --set imagePullSecrets[0].name=ghcr-secret \
          --namespace=default

    - name: Debug deployment
      run: |
        echo "Pod details:"
        kubectl get pods -l app.kubernetes.io/name=leo -o wide
        echo "\nPod description:"
        kubectl describe pod -l app.kubernetes.io/name=leo