name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/leo:latest

    - name: Verify image
      run: |
        docker pull ghcr.io/${{ github.repository_owner }}/leo:latest
        echo "Image details:"
        docker inspect ghcr.io/${{ github.repository_owner }}/leo:latest

    - name: Setup kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Create image pull secret
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GITHUB_TOKEN }} \
          --docker-email=${{ github.actor }}@users.noreply.github.com

    - name: Verify secret
      run: |
        echo "Checking secret:"
        kubectl get secret ghcr-secret -o yaml

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install leo ./helm/leo \
          --set leo.image=ghcr.io/${{ github.repository_owner }}/leo \
          --set leo.pullPolicy=Always \
          --set imagePullSecrets[0].name=ghcr-secret

    - name: Debug deployment
      run: |
        echo "Waiting for pod to be created..."
        sleep 10
        kubectl get pods
        kubectl describe pod -l app.kubernetes.io/name=leo